esdk: use 'rm -rf' instead of shutil.rmtree
use 'rm -rf' instead shutil.rmtree, because the latter will first opendir before removing it.
e.g.,
mkdir test-rmtree && mkdir -m 000 test-rmtree/dir000
In python3 shell, shutil.rmtree('test-rmtree')
   dirfd = os.open(entry.name, os.O_RDONLY, dir_fd=topfd)
   PermissionError: [Errno 13] Permission denied: 'dir000'

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>